version: '3.1'

services:

  scheduler:
    build: ./luigid/
    restart: always
    ports:
      - 8082:8082

  db:
    image: mysql
    restart: always
    ports:
      - "33060:3306"
    network_mode: "host"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: workflow
      MYSQL_PASSWORD: exercise
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: "host"